from lib.reports.DQReport import DQReport
from lib.reports.BaseReport import BaseReport


class Report0106(BaseReport):
    def init_report(self) -> None:
        self.report = DQReport(name='report0106', title='Geometrie is consistent met GeometrieArtefact',
                               spreadsheet_id='1x9g0b_wQtLgkxnAwR_lffzVLdS3PElb3mLWtqItqkig', datasource='ArangoDB',
                               persistent_column='K',
                               excel_filename='[RSA] Geometrie is consistent met GeometrieArtefact.xlsx',)

        self.report.result_query = """
            LET geometry_artefacts = [
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Baanlichaam', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#BlindePut', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Ecoduct', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Ecoduiker', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Ecokoker', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Ecotunnel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Ecovallei', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Fietstelinstallatie', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Gebouw', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#GecombineerdePut', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#GeluidwerendeConstructie', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#GroepDwarseMarkeringEnFiguratie', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#GroepMarkering', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Gronddam', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Hulppost', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#InspectieputRiolering', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#IPBackbone', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#L2AccessStructuur', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Link', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Lokaal', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Luchtkwaliteitsensor', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#MIVInstallatie', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Onderbord', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Pad', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Rioleringsstelsel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Slagboom', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Trajectcontrole', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#VerkeersbordConcept', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Verkeersbordopstelling', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#VerkeersbordVerkeersteken', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#VLAN', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Wegberm', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/installatie#Zpad', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Aansluitmof', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Aansluitopening', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Aanstraalverlichting', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Afmetingsensor', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Afscherming', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Afsluiter', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Aftakking', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#AIDModule', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#AnalogeHoppinzuil', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#ANPRCamera', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Antenne', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#AntiParkeerpaal', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Armatuurcontroller', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Audioversterker', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Batterij', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Bel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BeschermingWapening', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanBetonstraatsteen', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanBetontegel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanGebakkenStraatsteen', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanGrasbetontegel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanKassei', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanMozaiekkei', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BestratingVanNatuursteentegel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Bestrijking', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Bevestigingsbeugel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BijzonderGeluidsschermelement', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Binnenverlichtingstoestel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BitumineuzeLaag', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BloemrijkGlanshavergrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BloemrijkGraslandGraslandfase4', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BloemrijkStruisgrasgrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BloemrijkVochtigTotNatGrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BoogpaalVerkeerslicht', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Boom', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Boombrug', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Bouwput', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Bovenbouw', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Braam', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Brandblusser', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Brandhaspel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Brandleiding', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Brandnetelruigte', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#BremEnGaspeldoornstruweel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Buisbekleding', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Cabine', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Cabinecontroller', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Calamiteitendoorsteek', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#CalamiteitsBord', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Camera', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Cementbetonverharding', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Cluster', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Codeklavier', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#ColloidaalBeton', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Combilantaarn', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#ConstructieSokkel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Contactor', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Contactpunt', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Container', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Contourverlichting', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Damwand', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DetectieCamera', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Dieselgenerator', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Dilatatie', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Divergentiepuntbebakeningselement', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DNBHoogspanning', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DNBLaagspanning', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Dolomietverharding', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DominantGraslandfase2', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Dongle', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Doorgang', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Doornstruweel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Draineerbuis', geen_geometrie: '0', punt3D: '1', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Drukknop', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Drukverhogingsgroep', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Duikschot', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Duingrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DunneOverlaging', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DwarseMarkering', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DwarseMarkeringVerschuind', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Dwerghavergrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DwergstruikvegetatieHeidesoorten', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynamischeVluchtwegindicatie', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordExternePU', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordOpMaat', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordPK', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordRSS', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordRVMS', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordVMS', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DynBordZ30', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#EcoPoort', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Ecoraster', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Eindstuk', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#EnergiemeterAWV', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#EnergiemeterDerden', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#EnergiemeterDNB', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#EnergiemeterDNBPiek', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#EnergiemeterDNBReactief', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Exoten', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#ExterneDetectie', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#FieldOfView', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Fietslantaarn', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#FietstelDisplay', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Fietstelsysteem', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#FiguratieMarkering', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#FiguratieMarkeringVerschuind', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#ForfaitaireAansluiting', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Funderingsmassief', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Funderingsplaat', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Galgpaal', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GeexpandeerdPolystyreen', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GekleurdWegvlakMarkering', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Geleideconstructie', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Geleidingsverlichting', geen_geometrie: '0', punt3D: '1', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Geleidingswand', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GeluidswerendeConstructie', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Geotextiel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GetesteBeginconstructie', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GPU', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GrasKruidenmixGraslandfase3', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Grasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Grasmat', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#GrassenmixGraslandfase1', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Grindgazon', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Haag', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Handbediening', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Handwiel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Hardware', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Heestermassief', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#HeischraalGrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Hoofdschakelaar', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Hoogtedetectie', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#HSBeveiligingscel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#HSCabine', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Huisaansluitput', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Hulppostkast', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Hulpstuk', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Hydrant', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Iepenstruweel', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#IndoorKast', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Infiltratievoorziening', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#IntercomServer', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#IntercomToestel', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#InvasieveExoten', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#InwendigVerlichtPictogram', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#IOKaart', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#IpPowerSwitch', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#ITSapp', geen_geometrie: '1', punt3D: '0', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Kabelmof', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KabelnetToegang', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Kalkgrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KalkrijkKamgrasland', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Kamer', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KantstrookAfw', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KantstrookStd', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Klimatisatie', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Klimvorm', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Knipperlantaarn', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Kopmuur', geen_geometrie: '0', punt3D: '0', lijn3D: '0', polygoon3D: '1'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KringsBerliner', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Laagspanningsbord', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#LEDDriver', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#LetterCijferMarkering', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#LetterMarkeringVerschaald', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Lichtmast', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Lichtsensor', geen_geometrie: '0', punt3D: '1', lijn3D: '0', polygoon3D: '0'},
              {uri: 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#LijnvormigElementMarkering', geen_geometrie: '0', punt3D: '0', lijn3D: '1', polygoon3D: '0'}
            ]

            FOR a IN assets
              FILTER a.AIMDBStatus_isActief == true
              LET at = DOCUMENT(CONCAT("assettypes/", a.assettype_key))
              FILTER at != null

              LET ga = FIRST(
                FOR g IN geometry_artefacts
                  FILTER g.uri == at.uri
                  RETURN g
              )
              FILTER ga != null

              LET wkt_string = a.wkt
              LET is_point = wkt_string != null AND REGEX_TEST(wkt_string, 'POINT Z', true)
              LET is_line = wkt_string != null AND REGEX_TEST(wkt_string, 'LINESTRING Z', true)
              LET is_polygon = wkt_string != null AND REGEX_TEST(wkt_string, 'POLYGON Z', true)
              LET geometry_type = is_point ? 'punt3D' : (is_line ? 'lijn3D' : (is_polygon ? 'polygoon3D' : 'geen_geometrie'))

              FILTER (geometry_type == 'punt3D' AND ga.punt3D == '0')
                 OR (geometry_type == 'lijn3D' AND ga.lijn3D == '0')
                 OR (geometry_type == 'polygoon3D' AND ga.polygoon3D == '0')
                 OR (geometry_type == 'geen_geometrie' AND ga.geen_geometrie == '0')

              SORT at.naam ASC, geometry_type ASC, a.toestand ASC

              RETURN {
                uuid: a._key,
                naam: at.naam,
                wkt_string: LEFT(wkt_string, 50),
                level_of_geometrie: null,
                actief: a.AIMDBStatus_isActief,
                toestand: a.toestand,
                assettype_uri: at.uri,
                OTL_actuele_geometrie: geometry_type,
                GA_verwachte_geometrie: CONCAT(
                  ga.geen_geometrie == '1' ? 'geen_geometrie ' : '',
                  ga.punt3D == '1' ? 'punt3D ' : '',
                  ga.lijn3D == '1' ? 'lijn3D ' : '',
                  ga.polygoon3D == '1' ? 'polygoon3D ' : ''
                ),
                GA_Versie: 'GA_2.13.0'
              }
            """

    def run_report(self, sender) -> None:
        self.report.run_report(sender=sender)
